export const jobDetail = {
  id: 'testid',
  type: 'Full Time',
  url: 'https://url/positions/testid',
  created_at: 'Sun Nov 08 23:03:35 UTC 2020',
  company: 'TestCompany',
  company_url: 'https://www.test.com',
  location: 'New York City',
  title: 'Full Stack Engineer',
  description:
    '\u003cp\u003eResoluteAI is a fast-growth data aggregation and intelligent search startup, with a mission to enable scientifically driven organizations to make their next big discovery. Our tools allow our clients to find relevant results in an efficient manner, across patents, clinical trials, publications, drug and medical device datasets, and within their own internal corporate documents (enterprise search). We accomplish this through our proprietary machine learning algorithms. We are proud to count amongst our clients two of the top four (and five of the top twelve) global pharmaceutical firms by market cap.\u003c/p\u003e\n\u003cp\u003eWe are looking for full-stack developers to help build out our capabilities as we continue to grow.\u003c/p\u003e\n\u003cp\u003eDuties and Responsibilities:\u003c/p\u003e\n\u003cul\u003e\n\u003cli\u003eIntegrate public domain datasets into the search platform using our ETL framework.\u003c/li\u003e\n\u003cli\u003eDesign and implement new features that integrate and highlight the various public datasets.\u003c/li\u003e\n\u003cli\u003eWork with various external enterprise search APIs to ingest and enrich clients’ documents for search.\u003c/li\u003e\n\u003cli\u003eAssist machine learning engineers with deploying their models into production\u003c/li\u003e\n\u003cli\u003eCommunicate directly with clients on requirements, progress, and setting expectations.\u003c/li\u003e\n\u003cli\u003eAssist with bug fixes and writing of regression and unit tests.\u003c/li\u003e\n\u003c/ul\u003e\n\u003cp\u003eEducation and Previous Experience:\u003c/p\u003e\n\u003cul\u003e\n\u003cli\u003eBachelor’s degree in Computer Science, or equivalent experience in software development\u003c/li\u003e\n\u003cli\u003e5+ years in related experience and training\u003c/li\u003e\n\u003c/ul\u003e\n\u003cp\u003eKnowledge and Skills:\u003c/p\u003e\n\u003cul\u003e\n\u003cli\u003eStrongly skilled in Python. Experience with SQL and an ORM (e.g. sqlalchemy).\u003c/li\u003e\n\u003cli\u003eCan hold your own on the frontend UI in ReactJS\u003c/li\u003e\n\u003cli\u003eComfortable working with Docker and in a Linux environment\u003c/li\u003e\n\u003cli\u003eExperience with ElasticSearch – very strong plus\u003c/li\u003e\n\u003cli\u003eExperience with Elastic Map Reduce or Spark is a plus\u003c/li\u003e\n\u003cli\u003eKnowledge of networking, especially AWS services and infrastructure is a plus\u003c/li\u003e\n\u003cli\u003eMust have a self-starter mentality and willingness to dig deep into the code.\u003c/li\u003e\n\u003cli\u003eAbility to own your work and adopt an outcomes-based approach, in a fast paced environment of quickly evolving requirements.\u003c/li\u003e\n\u003c/ul\u003e\n\u003cp\u003eWhat we offer:\u003c/p\u003e\n\u003cul\u003e\n\u003cli\u003eCompetitive salary\u003c/li\u003e\n\u003cli\u003eFull benefits (Medical, Dental, Vision, FSA, Commuter benefit)\u003c/li\u003e\n\u003cli\u003e401(k) and matching\u003c/li\u003e\n\u003cli\u003eEquity in the company\u003c/li\u003e\n\u003cli\u003eUnlimited Paid Time Off\u003c/li\u003e\n\u003cli\u003eFlexible Work Environment\u003c/li\u003e\n\u003c/ul\u003e\n',
  how_to_apply:
    '\u003cp\u003ePlease apply at the following website:\n\u003ca href="https://resoluteai.applytojob.com/apply/qEBd0FBx4a/Full-Stack-Developer?source=Github"\u003ehttps://resoluteai.applytojob.com/apply/qEBd0FBx4a/Full-Stack-Developer?source=Github\u003c/a\u003e\u003c/p\u003e\n',
  company_logo: 'https://url/test',
};

export const jobs = [
  {
    id: 'testid',
    type: 'Full Time',
    url: 'https://url/positions/testid',
    created_at: 'Sun Nov 08 23:03:35 UTC 2020',
    company: 'TestCompany',
    company_url: 'https://www.test.com',
    location: 'New York City',
    title: 'Full Stack Engineer',
    description:
      '\u003cp\u003eResoluteAI is a fast-growth data aggregation and intelligent search startup, with a mission to enable scientifically driven organizations to make their next big discovery. Our tools allow our clients to find relevant results in an efficient manner, across patents, clinical trials, publications, drug and medical device datasets, and within their own internal corporate documents (enterprise search). We accomplish this through our proprietary machine learning algorithms. We are proud to count amongst our clients two of the top four (and five of the top twelve) global pharmaceutical firms by market cap.\u003c/p\u003e\n\u003cp\u003eWe are looking for full-stack developers to help build out our capabilities as we continue to grow.\u003c/p\u003e\n\u003cp\u003eDuties and Responsibilities:\u003c/p\u003e\n\u003cul\u003e\n\u003cli\u003eIntegrate public domain datasets into the search platform using our ETL framework.\u003c/li\u003e\n\u003cli\u003eDesign and implement new features that integrate and highlight the various public datasets.\u003c/li\u003e\n\u003cli\u003eWork with various external enterprise search APIs to ingest and enrich clients’ documents for search.\u003c/li\u003e\n\u003cli\u003eAssist machine learning engineers with deploying their models into production\u003c/li\u003e\n\u003cli\u003eCommunicate directly with clients on requirements, progress, and setting expectations.\u003c/li\u003e\n\u003cli\u003eAssist with bug fixes and writing of regression and unit tests.\u003c/li\u003e\n\u003c/ul\u003e\n\u003cp\u003eEducation and Previous Experience:\u003c/p\u003e\n\u003cul\u003e\n\u003cli\u003eBachelor’s degree in Computer Science, or equivalent experience in software development\u003c/li\u003e\n\u003cli\u003e5+ years in related experience and training\u003c/li\u003e\n\u003c/ul\u003e\n\u003cp\u003eKnowledge and Skills:\u003c/p\u003e\n\u003cul\u003e\n\u003cli\u003eStrongly skilled in Python. Experience with SQL and an ORM (e.g. sqlalchemy).\u003c/li\u003e\n\u003cli\u003eCan hold your own on the frontend UI in ReactJS\u003c/li\u003e\n\u003cli\u003eComfortable working with Docker and in a Linux environment\u003c/li\u003e\n\u003cli\u003eExperience with ElasticSearch – very strong plus\u003c/li\u003e\n\u003cli\u003eExperience with Elastic Map Reduce or Spark is a plus\u003c/li\u003e\n\u003cli\u003eKnowledge of networking, especially AWS services and infrastructure is a plus\u003c/li\u003e\n\u003cli\u003eMust have a self-starter mentality and willingness to dig deep into the code.\u003c/li\u003e\n\u003cli\u003eAbility to own your work and adopt an outcomes-based approach, in a fast paced environment of quickly evolving requirements.\u003c/li\u003e\n\u003c/ul\u003e\n\u003cp\u003eWhat we offer:\u003c/p\u003e\n\u003cul\u003e\n\u003cli\u003eCompetitive salary\u003c/li\u003e\n\u003cli\u003eFull benefits (Medical, Dental, Vision, FSA, Commuter benefit)\u003c/li\u003e\n\u003cli\u003e401(k) and matching\u003c/li\u003e\n\u003cli\u003eEquity in the company\u003c/li\u003e\n\u003cli\u003eUnlimited Paid Time Off\u003c/li\u003e\n\u003cli\u003eFlexible Work Environment\u003c/li\u003e\n\u003c/ul\u003e\n',
    how_to_apply:
      '\u003cp\u003ePlease apply at the following website:\n\u003ca href="https://resoluteai.applytojob.com/apply/qEBd0FBx4a/Full-Stack-Developer?source=Github"\u003ehttps://resoluteai.applytojob.com/apply/qEBd0FBx4a/Full-Stack-Developer?source=Github\u003c/a\u003e\u003c/p\u003e\n',
    company_logo: 'https://url/test',
  },
];

export const multiJobsMultiPage = [
  {
    id: 'testid1',
    type: 'Full Time',
    url: 'https://url/positions/testid',
    created_at: 'Sun Nov 08 23:03:35 UTC 2020',
    company: 'TestCompany',
    company_url: 'https://www.test.com',
    location: 'CCC',
    title: 'Full Stack Engineer',
    description: 'desc',
    how_to_apply: 'how to apply',
  },
  {
    id: 'testid2',
    type: 'Full Time',
    url: 'https://url/positions/testid',
    created_at: 'Sun Nov 08 23:03:35 UTC 2020',
    company: 'TestCompany',
    company_url: 'https://www.test.com',
    location: 'DDD',
    title: 'Full Stack Engineer',
    description: 'desc',
    how_to_apply: 'how to apply',
  },
  {
    id: 'testid3',
    type: 'Full Time',
    url: 'https://url/positions/testid',
    created_at: 'Sun Nov 08 23:03:35 UTC 2020',
    company: 'TestCompany',
    company_url: 'https://www.test.com',
    location: 'BBB',
    title: 'Full Stack Engineer',
    description: 'desc',
    how_to_apply: 'how to apply',
  },
  {
    id: 'testid4',
    type: 'Full Time',
    url: 'https://url/positions/testid',
    created_at: 'Sun Nov 08 23:03:35 UTC 2020',
    company: 'TestCompany',
    company_url: 'https://www.test.com',
    location: 'AAA',
    title: 'Full Stack Engineer',
    description: 'desc',
    how_to_apply: 'how to apply',
  },
  {
    id: 'testid4',
    type: 'Full Time',
    url: 'https://url/positions/testid',
    created_at: 'Sun Nov 08 23:03:35 UTC 2020',
    company: 'TestCompany',
    company_url: 'https://www.test.com',
    location: 'EEE',
    title: 'Full Stack Engineer',
    description: 'desc',
    how_to_apply: 'how to apply',
  },
  {
    id: 'testid4',
    type: 'Full Time',
    url: 'https://url/positions/testid',
    created_at: 'Sun Nov 08 23:03:35 UTC 2020',
    company: 'TestCompany',
    company_url: 'https://www.test.com',
    location: 'FFF',
    title: 'Full Stack Engineer',
    description: 'desc',
    how_to_apply: 'how to apply',
  },
  {
    id: 'testid4',
    type: 'Full Time',
    url: 'https://url/positions/testid',
    created_at: 'Sun Nov 08 23:03:35 UTC 2020',
    company: 'TestCompany',
    company_url: 'https://www.test.com',
    location: 'GGG',
    title: 'Full Stack Engineer',
    description: 'desc',
    how_to_apply: 'how to apply',
  },
  {
    id: 'testid4',
    type: 'Full Time',
    url: 'https://url/positions/testid',
    created_at: 'Sun Nov 08 23:03:35 UTC 2020',
    company: 'TestCompany',
    company_url: 'https://www.test.com',
    location: 'HHH',
    title: 'Full Stack Engineer',
    description: 'desc',
    how_to_apply: 'how to apply',
  },
  {
    id: 'testid4',
    type: 'Full Time',
    url: 'https://url/positions/testid',
    created_at: 'Sun Nov 08 23:03:35 UTC 2020',
    company: 'TestCompany',
    company_url: 'https://www.test.com',
    location: 'III',
    title: 'Full Stack Engineer',
    description: 'desc',
    how_to_apply: 'how to apply',
  },
  {
    id: 'testid4',
    type: 'Full Time',
    url: 'https://url/positions/testid',
    created_at: 'Sun Nov 08 23:03:35 UTC 2020',
    company: 'TestCompany',
    company_url: 'https://www.test.com',
    location: 'JJJ',
    title: 'Full Stack Engineer',
    description: 'desc',
    how_to_apply: 'how to apply',
  },
  {
    id: 'testid4',
    type: 'Full Time',
    url: 'https://url/positions/testid',
    created_at: 'Sun Nov 08 23:03:35 UTC 2020',
    company: 'TestCompany',
    company_url: 'https://www.test.com',
    location: 'JJJ',
    title: 'Full Stack Engineer',
    description: 'desc',
    how_to_apply: 'how to apply',
  },
  {
    id: 'testid4',
    type: 'Full Time',
    url: 'https://url/positions/testid',
    created_at: 'Sun Nov 08 23:03:35 UTC 2020',
    company: 'TestCompany',
    company_url: 'https://www.test.com',
    location: 'KKK',
    title: 'Full Stack Engineer',
    description: 'desc',
    how_to_apply: 'how to apply',
  },
  {
    id: 'testid4',
    type: 'Full Time',
    url: 'https://url/positions/testid',
    created_at: 'Sun Nov 08 23:03:35 UTC 2020',
    company: 'TestCompany',
    company_url: 'https://www.test.com',
    location: 'LLL',
    title: 'Full Stack Engineer',
    description: 'desc',
    how_to_apply: 'how to apply',
  },
  {
    id: 'testid4',
    type: 'Full Time',
    url: 'https://url/positions/testid',
    created_at: 'Sun Nov 08 23:03:35 UTC 2020',
    company: 'TestCompany',
    company_url: 'https://www.test.com',
    location: 'MMM',
    title: 'Full Stack Engineer',
    description: 'desc',
    how_to_apply: 'how to apply',
  },
  {
    id: 'testid4',
    type: 'Full Time',
    url: 'https://url/positions/testid',
    created_at: 'Sun Nov 08 23:03:35 UTC 2020',
    company: 'TestCompany',
    company_url: 'https://www.test.com',
    location: 'NNN',
    title: 'Full Stack Engineer',
    description: 'desc',
    how_to_apply: 'how to apply',
  },
  {
    id: 'testid4',
    type: 'Full Time',
    url: 'https://url/positions/testid',
    created_at: 'Sun Nov 08 23:03:35 UTC 2020',
    company: 'TestCompany',
    company_url: 'https://www.test.com',
    location: 'OOO',
    title: 'Full Stack Engineer',
    description: 'desc',
    how_to_apply: 'how to apply',
  },
  {
    id: 'testid4',
    type: 'Full Time',
    url: 'https://url/positions/testid',
    created_at: 'Sun Nov 08 23:03:35 UTC 2020',
    company: 'TestCompany',
    company_url: 'https://www.test.com',
    location: 'PPP',
    title: 'Full Stack Engineer',
    description: 'desc',
    how_to_apply: 'how to apply',
  },
  {
    id: 'testid4',
    type: 'Full Time',
    url: 'https://url/positions/testid',
    created_at: 'Sun Nov 08 23:03:35 UTC 2020',
    company: 'TestCompany',
    company_url: 'https://www.test.com',
    location: 'QQQ',
    title: 'Full Stack Engineer',
    description: 'desc',
    how_to_apply: 'how to apply',
  },
  {
    id: 'testid4',
    type: 'Full Time',
    url: 'https://url/positions/testid',
    created_at: 'Sun Nov 08 23:03:35 UTC 2020',
    company: 'TestCompany',
    company_url: 'https://www.test.com',
    location: 'RRR',
    title: 'Full Stack Engineer',
    description: 'desc',
    how_to_apply: 'how to apply',
  },
  {
    id: 'testid4',
    type: 'Full Time',
    url: 'https://url/positions/testid',
    created_at: 'Sun Nov 08 23:03:35 UTC 2020',
    company: 'TestCompany',
    company_url: 'https://www.test.com',
    location: 'SSS',
    title: 'Full Stack Engineer',
    description: 'desc',
    how_to_apply: 'how to apply',
  },
  {
    id: 'testid4',
    type: 'Full Time',
    url: 'https://url/positions/testid',
    created_at: 'Sun Nov 08 23:03:35 UTC 2020',
    company: 'TestCompany',
    company_url: 'https://www.test.com',
    location: 'TTT',
    title: 'Full Stack Engineer',
    description: 'desc',
    how_to_apply: 'how to apply',
  },
  {
    id: 'testid4',
    type: 'Full Time',
    url: 'https://url/positions/testid',
    created_at: 'Sun Nov 08 23:03:35 UTC 2020',
    company: 'TestCompany',
    company_url: 'https://www.test.com',
    location: 'UUU',
    title: 'Full Stack Engineer',
    description: 'desc',
    how_to_apply: 'how to apply',
  },
  {
    id: 'testid4',
    type: 'Full Time',
    url: 'https://url/positions/testid',
    created_at: 'Sun Nov 08 23:03:35 UTC 2020',
    company: 'TestCompany',
    company_url: 'https://www.test.com',
    location: 'VVV',
    title: 'Full Stack Engineer',
    description: 'desc',
    how_to_apply: 'how to apply',
  },
  {
    id: 'testid4',
    type: 'Full Time',
    url: 'https://url/positions/testid',
    created_at: 'Sun Nov 08 23:03:35 UTC 2020',
    company: 'TestCompany',
    company_url: 'https://www.test.com',
    location: 'WWW',
    title: 'Full Stack Engineer',
    description: 'desc',
    how_to_apply: 'how to apply',
  },
  {
    id: 'testid4',
    type: 'Full Time',
    url: 'https://url/positions/testid',
    created_at: 'Sun Nov 08 23:03:35 UTC 2020',
    company: 'TestCompany',
    company_url: 'https://www.test.com',
    location: 'XXX',
    title: 'Full Stack Engineer',
    description: 'desc',
    how_to_apply: 'how to apply',
  },
  {
    id: 'testid4',
    type: 'Full Time',
    url: 'https://url/positions/testid',
    created_at: 'Sun Nov 08 23:03:35 UTC 2020',
    company: 'TestCompany',
    company_url: 'https://www.test.com',
    location: 'YYY',
    title: 'Full Stack Engineer',
    description: 'desc',
    how_to_apply: 'how to apply',
  },
  {
    id: 'testid4',
    type: 'Full Time',
    url: 'https://url/positions/testid',
    created_at: 'Sun Nov 08 23:03:35 UTC 2020',
    company: 'TestCompany',
    company_url: 'https://www.test.com',
    location: 'ZZZ',
    title: 'Full Stack Engineer',
    description: 'desc',
    how_to_apply: 'how to apply',
  },
];

export const multiJobs = [
  {
    id: 'testid1',
    type: 'Full Time',
    url: 'https://url/positions/testid',
    created_at: 'Sun Nov 08 23:03:35 UTC 2020',
    company: 'TestCompany',
    company_url: 'https://www.test.com',
    location: 'CCC',
    title: 'Full Stack Engineer',
    description:
      '\u003cp\u003eResoluteAI is a fast-growth data aggregation and intelligent search startup, with a mission to enable scientifically driven organizations to make their next big discovery. Our tools allow our clients to find relevant results in an efficient manner, across patents, clinical trials, publications, drug and medical device datasets, and within their own internal corporate documents (enterprise search). We accomplish this through our proprietary machine learning algorithms. We are proud to count amongst our clients two of the top four (and five of the top twelve) global pharmaceutical firms by market cap.\u003c/p\u003e\n\u003cp\u003eWe are looking for full-stack developers to help build out our capabilities as we continue to grow.\u003c/p\u003e\n\u003cp\u003eDuties and Responsibilities:\u003c/p\u003e\n\u003cul\u003e\n\u003cli\u003eIntegrate public domain datasets into the search platform using our ETL framework.\u003c/li\u003e\n\u003cli\u003eDesign and implement new features that integrate and highlight the various public datasets.\u003c/li\u003e\n\u003cli\u003eWork with various external enterprise search APIs to ingest and enrich clients’ documents for search.\u003c/li\u003e\n\u003cli\u003eAssist machine learning engineers with deploying their models into production\u003c/li\u003e\n\u003cli\u003eCommunicate directly with clients on requirements, progress, and setting expectations.\u003c/li\u003e\n\u003cli\u003eAssist with bug fixes and writing of regression and unit tests.\u003c/li\u003e\n\u003c/ul\u003e\n\u003cp\u003eEducation and Previous Experience:\u003c/p\u003e\n\u003cul\u003e\n\u003cli\u003eBachelor’s degree in Computer Science, or equivalent experience in software development\u003c/li\u003e\n\u003cli\u003e5+ years in related experience and training\u003c/li\u003e\n\u003c/ul\u003e\n\u003cp\u003eKnowledge and Skills:\u003c/p\u003e\n\u003cul\u003e\n\u003cli\u003eStrongly skilled in Python. Experience with SQL and an ORM (e.g. sqlalchemy).\u003c/li\u003e\n\u003cli\u003eCan hold your own on the frontend UI in ReactJS\u003c/li\u003e\n\u003cli\u003eComfortable working with Docker and in a Linux environment\u003c/li\u003e\n\u003cli\u003eExperience with ElasticSearch – very strong plus\u003c/li\u003e\n\u003cli\u003eExperience with Elastic Map Reduce or Spark is a plus\u003c/li\u003e\n\u003cli\u003eKnowledge of networking, especially AWS services and infrastructure is a plus\u003c/li\u003e\n\u003cli\u003eMust have a self-starter mentality and willingness to dig deep into the code.\u003c/li\u003e\n\u003cli\u003eAbility to own your work and adopt an outcomes-based approach, in a fast paced environment of quickly evolving requirements.\u003c/li\u003e\n\u003c/ul\u003e\n\u003cp\u003eWhat we offer:\u003c/p\u003e\n\u003cul\u003e\n\u003cli\u003eCompetitive salary\u003c/li\u003e\n\u003cli\u003eFull benefits (Medical, Dental, Vision, FSA, Commuter benefit)\u003c/li\u003e\n\u003cli\u003e401(k) and matching\u003c/li\u003e\n\u003cli\u003eEquity in the company\u003c/li\u003e\n\u003cli\u003eUnlimited Paid Time Off\u003c/li\u003e\n\u003cli\u003eFlexible Work Environment\u003c/li\u003e\n\u003c/ul\u003e\n',
    how_to_apply:
      '\u003cp\u003ePlease apply at the following website:\n\u003ca href="https://resoluteai.applytojob.com/apply/qEBd0FBx4a/Full-Stack-Developer?source=Github"\u003ehttps://resoluteai.applytojob.com/apply/qEBd0FBx4a/Full-Stack-Developer?source=Github\u003c/a\u003e\u003c/p\u003e\n',
    company_logo: 'https://url/test',
  },
  {
    id: 'testid2',
    type: 'Full Time',
    url: 'https://url/positions/testid',
    created_at: 'Sun Nov 08 23:03:35 UTC 2020',
    company: 'TestCompany',
    company_url: 'https://www.test.com',
    location: 'DDD',
    title: 'Full Stack Engineer',
    description:
      '\u003cp\u003eResoluteAI is a fast-growth data aggregation and intelligent search startup, with a mission to enable scientifically driven organizations to make their next big discovery. Our tools allow our clients to find relevant results in an efficient manner, across patents, clinical trials, publications, drug and medical device datasets, and within their own internal corporate documents (enterprise search). We accomplish this through our proprietary machine learning algorithms. We are proud to count amongst our clients two of the top four (and five of the top twelve) global pharmaceutical firms by market cap.\u003c/p\u003e\n\u003cp\u003eWe are looking for full-stack developers to help build out our capabilities as we continue to grow.\u003c/p\u003e\n\u003cp\u003eDuties and Responsibilities:\u003c/p\u003e\n\u003cul\u003e\n\u003cli\u003eIntegrate public domain datasets into the search platform using our ETL framework.\u003c/li\u003e\n\u003cli\u003eDesign and implement new features that integrate and highlight the various public datasets.\u003c/li\u003e\n\u003cli\u003eWork with various external enterprise search APIs to ingest and enrich clients’ documents for search.\u003c/li\u003e\n\u003cli\u003eAssist machine learning engineers with deploying their models into production\u003c/li\u003e\n\u003cli\u003eCommunicate directly with clients on requirements, progress, and setting expectations.\u003c/li\u003e\n\u003cli\u003eAssist with bug fixes and writing of regression and unit tests.\u003c/li\u003e\n\u003c/ul\u003e\n\u003cp\u003eEducation and Previous Experience:\u003c/p\u003e\n\u003cul\u003e\n\u003cli\u003eBachelor’s degree in Computer Science, or equivalent experience in software development\u003c/li\u003e\n\u003cli\u003e5+ years in related experience and training\u003c/li\u003e\n\u003c/ul\u003e\n\u003cp\u003eKnowledge and Skills:\u003c/p\u003e\n\u003cul\u003e\n\u003cli\u003eStrongly skilled in Python. Experience with SQL and an ORM (e.g. sqlalchemy).\u003c/li\u003e\n\u003cli\u003eCan hold your own on the frontend UI in ReactJS\u003c/li\u003e\n\u003cli\u003eComfortable working with Docker and in a Linux environment\u003c/li\u003e\n\u003cli\u003eExperience with ElasticSearch – very strong plus\u003c/li\u003e\n\u003cli\u003eExperience with Elastic Map Reduce or Spark is a plus\u003c/li\u003e\n\u003cli\u003eKnowledge of networking, especially AWS services and infrastructure is a plus\u003c/li\u003e\n\u003cli\u003eMust have a self-starter mentality and willingness to dig deep into the code.\u003c/li\u003e\n\u003cli\u003eAbility to own your work and adopt an outcomes-based approach, in a fast paced environment of quickly evolving requirements.\u003c/li\u003e\n\u003c/ul\u003e\n\u003cp\u003eWhat we offer:\u003c/p\u003e\n\u003cul\u003e\n\u003cli\u003eCompetitive salary\u003c/li\u003e\n\u003cli\u003eFull benefits (Medical, Dental, Vision, FSA, Commuter benefit)\u003c/li\u003e\n\u003cli\u003e401(k) and matching\u003c/li\u003e\n\u003cli\u003eEquity in the company\u003c/li\u003e\n\u003cli\u003eUnlimited Paid Time Off\u003c/li\u003e\n\u003cli\u003eFlexible Work Environment\u003c/li\u003e\n\u003c/ul\u003e\n',
    how_to_apply:
      '\u003cp\u003ePlease apply at the following website:\n\u003ca href="https://resoluteai.applytojob.com/apply/qEBd0FBx4a/Full-Stack-Developer?source=Github"\u003ehttps://resoluteai.applytojob.com/apply/qEBd0FBx4a/Full-Stack-Developer?source=Github\u003c/a\u003e\u003c/p\u003e\n',
    company_logo: 'https://url/test',
  },
  {
    id: 'testid3',
    type: 'Full Time',
    url: 'https://url/positions/testid',
    created_at: 'Sun Nov 08 23:03:35 UTC 2020',
    company: 'TestCompany',
    company_url: 'https://www.test.com',
    location: 'BBB',
    title: 'Full Stack Engineer',
    description:
      '\u003cp\u003eResoluteAI is a fast-growth data aggregation and intelligent search startup, with a mission to enable scientifically driven organizations to make their next big discovery. Our tools allow our clients to find relevant results in an efficient manner, across patents, clinical trials, publications, drug and medical device datasets, and within their own internal corporate documents (enterprise search). We accomplish this through our proprietary machine learning algorithms. We are proud to count amongst our clients two of the top four (and five of the top twelve) global pharmaceutical firms by market cap.\u003c/p\u003e\n\u003cp\u003eWe are looking for full-stack developers to help build out our capabilities as we continue to grow.\u003c/p\u003e\n\u003cp\u003eDuties and Responsibilities:\u003c/p\u003e\n\u003cul\u003e\n\u003cli\u003eIntegrate public domain datasets into the search platform using our ETL framework.\u003c/li\u003e\n\u003cli\u003eDesign and implement new features that integrate and highlight the various public datasets.\u003c/li\u003e\n\u003cli\u003eWork with various external enterprise search APIs to ingest and enrich clients’ documents for search.\u003c/li\u003e\n\u003cli\u003eAssist machine learning engineers with deploying their models into production\u003c/li\u003e\n\u003cli\u003eCommunicate directly with clients on requirements, progress, and setting expectations.\u003c/li\u003e\n\u003cli\u003eAssist with bug fixes and writing of regression and unit tests.\u003c/li\u003e\n\u003c/ul\u003e\n\u003cp\u003eEducation and Previous Experience:\u003c/p\u003e\n\u003cul\u003e\n\u003cli\u003eBachelor’s degree in Computer Science, or equivalent experience in software development\u003c/li\u003e\n\u003cli\u003e5+ years in related experience and training\u003c/li\u003e\n\u003c/ul\u003e\n\u003cp\u003eKnowledge and Skills:\u003c/p\u003e\n\u003cul\u003e\n\u003cli\u003eStrongly skilled in Python. Experience with SQL and an ORM (e.g. sqlalchemy).\u003c/li\u003e\n\u003cli\u003eCan hold your own on the frontend UI in ReactJS\u003c/li\u003e\n\u003cli\u003eComfortable working with Docker and in a Linux environment\u003c/li\u003e\n\u003cli\u003eExperience with ElasticSearch – very strong plus\u003c/li\u003e\n\u003cli\u003eExperience with Elastic Map Reduce or Spark is a plus\u003c/li\u003e\n\u003cli\u003eKnowledge of networking, especially AWS services and infrastructure is a plus\u003c/li\u003e\n\u003cli\u003eMust have a self-starter mentality and willingness to dig deep into the code.\u003c/li\u003e\n\u003cli\u003eAbility to own your work and adopt an outcomes-based approach, in a fast paced environment of quickly evolving requirements.\u003c/li\u003e\n\u003c/ul\u003e\n\u003cp\u003eWhat we offer:\u003c/p\u003e\n\u003cul\u003e\n\u003cli\u003eCompetitive salary\u003c/li\u003e\n\u003cli\u003eFull benefits (Medical, Dental, Vision, FSA, Commuter benefit)\u003c/li\u003e\n\u003cli\u003e401(k) and matching\u003c/li\u003e\n\u003cli\u003eEquity in the company\u003c/li\u003e\n\u003cli\u003eUnlimited Paid Time Off\u003c/li\u003e\n\u003cli\u003eFlexible Work Environment\u003c/li\u003e\n\u003c/ul\u003e\n',
    how_to_apply:
      '\u003cp\u003ePlease apply at the following website:\n\u003ca href="https://resoluteai.applytojob.com/apply/qEBd0FBx4a/Full-Stack-Developer?source=Github"\u003ehttps://resoluteai.applytojob.com/apply/qEBd0FBx4a/Full-Stack-Developer?source=Github\u003c/a\u003e\u003c/p\u003e\n',
    company_logo: 'https://url/test',
  },
  {
    id: 'testid4',
    type: 'Full Time',
    url: 'https://url/positions/testid',
    created_at: 'Sun Nov 08 23:03:35 UTC 2020',
    company: 'TestCompany',
    company_url: 'https://www.test.com',
    location: 'AAA',
    title: 'Full Stack Engineer',
    description:
      '\u003cp\u003eResoluteAI is a fast-growth data aggregation and intelligent search startup, with a mission to enable scientifically driven organizations to make their next big discovery. Our tools allow our clients to find relevant results in an efficient manner, across patents, clinical trials, publications, drug and medical device datasets, and within their own internal corporate documents (enterprise search). We accomplish this through our proprietary machine learning algorithms. We are proud to count amongst our clients two of the top four (and five of the top twelve) global pharmaceutical firms by market cap.\u003c/p\u003e\n\u003cp\u003eWe are looking for full-stack developers to help build out our capabilities as we continue to grow.\u003c/p\u003e\n\u003cp\u003eDuties and Responsibilities:\u003c/p\u003e\n\u003cul\u003e\n\u003cli\u003eIntegrate public domain datasets into the search platform using our ETL framework.\u003c/li\u003e\n\u003cli\u003eDesign and implement new features that integrate and highlight the various public datasets.\u003c/li\u003e\n\u003cli\u003eWork with various external enterprise search APIs to ingest and enrich clients’ documents for search.\u003c/li\u003e\n\u003cli\u003eAssist machine learning engineers with deploying their models into production\u003c/li\u003e\n\u003cli\u003eCommunicate directly with clients on requirements, progress, and setting expectations.\u003c/li\u003e\n\u003cli\u003eAssist with bug fixes and writing of regression and unit tests.\u003c/li\u003e\n\u003c/ul\u003e\n\u003cp\u003eEducation and Previous Experience:\u003c/p\u003e\n\u003cul\u003e\n\u003cli\u003eBachelor’s degree in Computer Science, or equivalent experience in software development\u003c/li\u003e\n\u003cli\u003e5+ years in related experience and training\u003c/li\u003e\n\u003c/ul\u003e\n\u003cp\u003eKnowledge and Skills:\u003c/p\u003e\n\u003cul\u003e\n\u003cli\u003eStrongly skilled in Python. Experience with SQL and an ORM (e.g. sqlalchemy).\u003c/li\u003e\n\u003cli\u003eCan hold your own on the frontend UI in ReactJS\u003c/li\u003e\n\u003cli\u003eComfortable working with Docker and in a Linux environment\u003c/li\u003e\n\u003cli\u003eExperience with ElasticSearch – very strong plus\u003c/li\u003e\n\u003cli\u003eExperience with Elastic Map Reduce or Spark is a plus\u003c/li\u003e\n\u003cli\u003eKnowledge of networking, especially AWS services and infrastructure is a plus\u003c/li\u003e\n\u003cli\u003eMust have a self-starter mentality and willingness to dig deep into the code.\u003c/li\u003e\n\u003cli\u003eAbility to own your work and adopt an outcomes-based approach, in a fast paced environment of quickly evolving requirements.\u003c/li\u003e\n\u003c/ul\u003e\n\u003cp\u003eWhat we offer:\u003c/p\u003e\n\u003cul\u003e\n\u003cli\u003eCompetitive salary\u003c/li\u003e\n\u003cli\u003eFull benefits (Medical, Dental, Vision, FSA, Commuter benefit)\u003c/li\u003e\n\u003cli\u003e401(k) and matching\u003c/li\u003e\n\u003cli\u003eEquity in the company\u003c/li\u003e\n\u003cli\u003eUnlimited Paid Time Off\u003c/li\u003e\n\u003cli\u003eFlexible Work Environment\u003c/li\u003e\n\u003c/ul\u003e\n',
    how_to_apply:
      '\u003cp\u003ePlease apply at the following website:\n\u003ca href="https://resoluteai.applytojob.com/apply/qEBd0FBx4a/Full-Stack-Developer?source=Github"\u003ehttps://resoluteai.applytojob.com/apply/qEBd0FBx4a/Full-Stack-Developer?source=Github\u003c/a\u003e\u003c/p\u003e\n',
    company_logo: 'https://url/test',
  },
];

export const listings = {
  error: false,
  errorMsg: '',
  listings: [
    {
      id: 'testid',
      type: 'Full Time',
      url: 'https://url/positions/testid',
      created_at: 'Sun Nov 08 23:03:35 UTC 2020',
      company: 'TestCompany',
      company_url: 'https://www.test.com',
      location: 'New York City',
      title: 'Full Stack Engineer',
      description:
        '\u003cp\u003eResoluteAI is a fast-growth data aggregation and intelligent search startup, with a mission to enable scientifically driven organizations to make their next big discovery. Our tools allow our clients to find relevant results in an efficient manner, across patents, clinical trials, publications, drug and medical device datasets, and within their own internal corporate documents (enterprise search). We accomplish this through our proprietary machine learning algorithms. We are proud to count amongst our clients two of the top four (and five of the top twelve) global pharmaceutical firms by market cap.\u003c/p\u003e\n\u003cp\u003eWe are looking for full-stack developers to help build out our capabilities as we continue to grow.\u003c/p\u003e\n\u003cp\u003eDuties and Responsibilities:\u003c/p\u003e\n\u003cul\u003e\n\u003cli\u003eIntegrate public domain datasets into the search platform using our ETL framework.\u003c/li\u003e\n\u003cli\u003eDesign and implement new features that integrate and highlight the various public datasets.\u003c/li\u003e\n\u003cli\u003eWork with various external enterprise search APIs to ingest and enrich clients’ documents for search.\u003c/li\u003e\n\u003cli\u003eAssist machine learning engineers with deploying their models into production\u003c/li\u003e\n\u003cli\u003eCommunicate directly with clients on requirements, progress, and setting expectations.\u003c/li\u003e\n\u003cli\u003eAssist with bug fixes and writing of regression and unit tests.\u003c/li\u003e\n\u003c/ul\u003e\n\u003cp\u003eEducation and Previous Experience:\u003c/p\u003e\n\u003cul\u003e\n\u003cli\u003eBachelor’s degree in Computer Science, or equivalent experience in software development\u003c/li\u003e\n\u003cli\u003e5+ years in related experience and training\u003c/li\u003e\n\u003c/ul\u003e\n\u003cp\u003eKnowledge and Skills:\u003c/p\u003e\n\u003cul\u003e\n\u003cli\u003eStrongly skilled in Python. Experience with SQL and an ORM (e.g. sqlalchemy).\u003c/li\u003e\n\u003cli\u003eCan hold your own on the frontend UI in ReactJS\u003c/li\u003e\n\u003cli\u003eComfortable working with Docker and in a Linux environment\u003c/li\u003e\n\u003cli\u003eExperience with ElasticSearch – very strong plus\u003c/li\u003e\n\u003cli\u003eExperience with Elastic Map Reduce or Spark is a plus\u003c/li\u003e\n\u003cli\u003eKnowledge of networking, especially AWS services and infrastructure is a plus\u003c/li\u003e\n\u003cli\u003eMust have a self-starter mentality and willingness to dig deep into the code.\u003c/li\u003e\n\u003cli\u003eAbility to own your work and adopt an outcomes-based approach, in a fast paced environment of quickly evolving requirements.\u003c/li\u003e\n\u003c/ul\u003e\n\u003cp\u003eWhat we offer:\u003c/p\u003e\n\u003cul\u003e\n\u003cli\u003eCompetitive salary\u003c/li\u003e\n\u003cli\u003eFull benefits (Medical, Dental, Vision, FSA, Commuter benefit)\u003c/li\u003e\n\u003cli\u003e401(k) and matching\u003c/li\u003e\n\u003cli\u003eEquity in the company\u003c/li\u003e\n\u003cli\u003eUnlimited Paid Time Off\u003c/li\u003e\n\u003cli\u003eFlexible Work Environment\u003c/li\u003e\n\u003c/ul\u003e\n',
      how_to_apply:
        '\u003cp\u003ePlease apply at the following website:\n\u003ca href="https://resoluteai.applytojob.com/apply/qEBd0FBx4a/Full-Stack-Developer?source=Github"\u003ehttps://resoluteai.applytojob.com/apply/qEBd0FBx4a/Full-Stack-Developer?source=Github\u003c/a\u003e\u003c/p\u003e\n',
      company_logo: 'https://url/test',
    },
  ],
};

export const jobdetails = {
  error: false,
  errorMsg: '',
  jobDetail: {
    id: 'testid',
    type: 'Full Time',
    url: 'https://url/positions/testid',
    created_at: 'Sun Nov 08 23:03:35 UTC 2020',
    company: 'TestCompany',
    company_url: 'https://www.test.com',
    location: 'New York City',
    title: 'Full Stack Engineer',
    description:
      '\u003cp\u003eResoluteAI is a fast-growth data aggregation and intelligent search startup, with a mission to enable scientifically driven organizations to make their next big discovery. Our tools allow our clients to find relevant results in an efficient manner, across patents, clinical trials, publications, drug and medical device datasets, and within their own internal corporate documents (enterprise search). We accomplish this through our proprietary machine learning algorithms. We are proud to count amongst our clients two of the top four (and five of the top twelve) global pharmaceutical firms by market cap.\u003c/p\u003e\n\u003cp\u003eWe are looking for full-stack developers to help build out our capabilities as we continue to grow.\u003c/p\u003e\n\u003cp\u003eDuties and Responsibilities:\u003c/p\u003e\n\u003cul\u003e\n\u003cli\u003eIntegrate public domain datasets into the search platform using our ETL framework.\u003c/li\u003e\n\u003cli\u003eDesign and implement new features that integrate and highlight the various public datasets.\u003c/li\u003e\n\u003cli\u003eWork with various external enterprise search APIs to ingest and enrich clients’ documents for search.\u003c/li\u003e\n\u003cli\u003eAssist machine learning engineers with deploying their models into production\u003c/li\u003e\n\u003cli\u003eCommunicate directly with clients on requirements, progress, and setting expectations.\u003c/li\u003e\n\u003cli\u003eAssist with bug fixes and writing of regression and unit tests.\u003c/li\u003e\n\u003c/ul\u003e\n\u003cp\u003eEducation and Previous Experience:\u003c/p\u003e\n\u003cul\u003e\n\u003cli\u003eBachelor’s degree in Computer Science, or equivalent experience in software development\u003c/li\u003e\n\u003cli\u003e5+ years in related experience and training\u003c/li\u003e\n\u003c/ul\u003e\n\u003cp\u003eKnowledge and Skills:\u003c/p\u003e\n\u003cul\u003e\n\u003cli\u003eStrongly skilled in Python. Experience with SQL and an ORM (e.g. sqlalchemy).\u003c/li\u003e\n\u003cli\u003eCan hold your own on the frontend UI in ReactJS\u003c/li\u003e\n\u003cli\u003eComfortable working with Docker and in a Linux environment\u003c/li\u003e\n\u003cli\u003eExperience with ElasticSearch – very strong plus\u003c/li\u003e\n\u003cli\u003eExperience with Elastic Map Reduce or Spark is a plus\u003c/li\u003e\n\u003cli\u003eKnowledge of networking, especially AWS services and infrastructure is a plus\u003c/li\u003e\n\u003cli\u003eMust have a self-starter mentality and willingness to dig deep into the code.\u003c/li\u003e\n\u003cli\u003eAbility to own your work and adopt an outcomes-based approach, in a fast paced environment of quickly evolving requirements.\u003c/li\u003e\n\u003c/ul\u003e\n\u003cp\u003eWhat we offer:\u003c/p\u003e\n\u003cul\u003e\n\u003cli\u003eCompetitive salary\u003c/li\u003e\n\u003cli\u003eFull benefits (Medical, Dental, Vision, FSA, Commuter benefit)\u003c/li\u003e\n\u003cli\u003e401(k) and matching\u003c/li\u003e\n\u003cli\u003eEquity in the company\u003c/li\u003e\n\u003cli\u003eUnlimited Paid Time Off\u003c/li\u003e\n\u003cli\u003eFlexible Work Environment\u003c/li\u003e\n\u003c/ul\u003e\n',
    how_to_apply:
      '\u003cp\u003ePlease apply at the following website:\n\u003ca href="https://resoluteai.applytojob.com/apply/qEBd0FBx4a/Full-Stack-Developer?source=Github"\u003ehttps://resoluteai.applytojob.com/apply/qEBd0FBx4a/Full-Stack-Developer?source=Github\u003c/a\u003e\u003c/p\u003e\n',
    company_logo: 'https://url/test',
  },
};
